services:
  - type: web
    name: thanks-shop-backend
    env: docker
    repo: https://github.com/dinhhthanhh/thanks-shop
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          name: thanks-shop-frontend
          type: static

  - type: static
    name: thanks-shop-frontend
    repo: https://github.com/dinhhthanhh/thanks-shop
    rootDir: frontend
    buildCommand: npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: thanks-shop-backend
          type: web
          property: url
        suffix: /api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
